_wandb:
    value:
        cli_version: 0.23.1
        e:
            7keboedqan2dhoncdw8j86mq98uaqtd2:
                apple:
                    ecpuCores: 4
                    gpuCores: 40
                    memoryGb: 48
                    name: Apple M4 Max
                    pcpuCores: 12
                    ramTotalBytes: "51539607552"
                codePath: training_scripts/main_balance.py
                codePathLocal: training_scripts/main_balance.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "994662584320"
                        used: "666217422848"
                email: stephen.zhu.05@gmail.com
                executable: /Users/steph/miniconda3/envs/sai_soccer/bin/python
                git:
                    commit: c8e7f0870bb9122103efc591090cb31264b96bae
                    remote: https://github.com/Ezimakyu/SAI_SoccerRL.git
                host: vpnduopool-10-251-173-93.near.illinois.edu
                memory:
                    total: "51539607552"
                os: macOS-15.2-arm64-arm-64bit
                program: /Users/steph/Desktop/booster_soccer_showdown/./training_scripts/main_balance.py
                python: CPython 3.11.14
                root: /Users/steph/Desktop/booster_soccer_showdown
                startedAt: "2026-01-04T01:41:37.552037Z"
                writerId: 7keboedqan2dhoncdw8j86mq98uaqtd2
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
ankle_stab_w:
    value: 0.1
batch_size:
    value: 256
emergency_step_w:
    value: 0.05
policy_clip:
    value: 0.35
push_up_w:
    value: 0.2
recovery_tilt:
    value: 0.35
stable_tilt:
    value: 0.15
timesteps:
    value: 400000
